# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 14:24
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('graduate', models.SmallIntegerField()),
                ('unit', models.CharField(max_length=512)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('im', models.CharField(blank=True, max_length=32, null=True)),
                ('wechat', models.CharField(blank=True, max_length=32, null=True)),
                ('short_word', models.CharField(blank=True, max_length=200, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
    ]
